### ISSUE TITLE
[BALIN - Dashboard] product index

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/balin-dashboard#33]
- [x] when use thousands data, got collapse, please check limit number for ajax
  (other works fine)
  ![thousands](https://cloud.githubusercontent.com/assets/5895063/12719895/71677dec-c92a-11e5-8cd0-0e91f8ff24b3.png)

**Comment by budi7** [comment]
working fine
![image](https://cloud.githubusercontent.com/assets/10555410/12741033/7a0b607c-c9ab-11e5-88ee-34dae2279d36.png)

**Comment by chelsymooy** [comment]
happen when connection down
