### ISSUE TITLE
tambah/edit varian

### ISSUE THREAD

**Issue by agilma** [ThunderID/balin-dashboard#59]
- [x] tambah varian baru muncul error ![screen shot 2016-09-27 at 10 44 02 am](https://cloud.githubusercontent.com/assets/4099329/18863937/10f10fc8-84be-11e6-9aff-88d4663fe99a.png)
- [x] ketika ingin mengedit varian muncul error  ![screen shot 2016-09-27 at 10 45 44 am](https://cloud.githubusercontent.com/assets/4099329/18863962/2a90df80-84be-11e6-8259-16a80090e807.png)

**Comment by chelsymooy** [comment]
Me Here

**Comment by chelsymooy** [comment]
Fixed in https://github.com/ThunderID/BALIN-API-V2/commit/da350549d28066d989b30d38e3f80940812d3337
