### ISSUE TITLE
error kategori product

### ISSUE THREAD

**Issue by agilma** [ThunderID/balin-dashboard#61]
waktu mengklik kategori detail muncul pesan error, hanya beberapa kategori yang muncul error seperti ini
![screen shot 2016-09-27 at 11 28 00 am](https://cloud.githubusercontent.com/assets/4099329/18864173/46152846-84bf-11e6-9aaa-5e9f3ec2ea4b.png)

**Comment by chelsymooy** [comment]
aku disini

**Comment by chelsymooy** [comment]
permasalahannya karena _uppercase_

TO BE NOTED
kalau server linux mesti case sensitive,
modalDelete dan modaldelete dianggap berbeda
@budi7 @uchuy77
