### ISSUE TITLE
halaman konfigurasi 

### ISSUE THREAD

**Issue by agilma** [ThunderID/balin-dashboard#62]
- [x] ketika klik detail di halaman konfigurasi admin lalu klik detail, muncul pesan error ![screen shot 2016-09-27 at 2 38 14 pm](https://cloud.githubusercontent.com/assets/4099329/18864422/807c56de-84c0-11e6-97a1-32a778d497d7.png)
- [ ] **[enhancement]** ketika edit/tambah di tab konfigurasi website waktu klik simpan pindah ke tab 1 
- [x] di konfigurasi website dibagian instagram tidak bisa delete item ![screen shot 2016-09-27 at 3 20 46 pm](https://cloud.githubusercontent.com/assets/4099329/18865548/0a2d9ee2-84c6-11e6-9da4-5f490a2c63e1.png)
- [x] di tab term & condition ketika mengubah datanya setelah disimpan data tetap seperti semula, tidak menyimpan
- [x] di tab why join sama seperti term & condition

**Comment by chelsymooy** [comment]
me here

**Comment by chelsymooy** [comment]
me no longer here

**Comment by chelsymooy** [comment]
mas @budi7 3 checklists terakhir assign ke kamu ya

di tempatku websitecontrollernya gada banner, takutnya ntar ke replace

**Comment by budi7** [comment]
doing
