### ISSUE TITLE
halaman data pelanggan

### ISSUE THREAD

**Issue by agilma** [ThunderID/balin-dashboard#63]
email dari data pelanggan setelah next page, email data pelangga ada beberapa diganti email protected otomatis diubah oleh server
![screen shot 2016-09-27 at 3 34 33 pm](https://cloud.githubusercontent.com/assets/4099329/18866018/322f9c40-84c8-11e6-8dd0-234af76f0c74.png)

**Comment by chelsymooy** [comment]
You must enable Javascript in your browser in order to decode the e-mail address.

**Comment by chelsymooy** [comment]
' You must enable Javascript in your browser in order to decode the e-mail address.'
