### ISSUE TITLE
promosi

### ISSUE THREAD

**Issue by agilma** [ThunderID/balin-dashboard#64]
- [x] di halaman promosi voucher, voucher tidak bisa dihapus modal tidak jalan ketika diklik button delete ![screen shot 2016-09-27 at 3 56 42 pm](https://cloud.githubusercontent.com/assets/4099329/18866724/6b1b9484-84cb-11e6-9892-4aa04560b382.png)
- [x] waktu klik menu halaman diskon muncul pesan error  ![screen shot 2016-09-27 at 3 58 20 pm](https://cloud.githubusercontent.com/assets/4099329/18866791/b1096d40-84cb-11e6-96e0-ef58279f1f53.png)

**Comment by chelsymooy** [comment]
Me Here
