### ISSUE TITLE
Laporan

### ISSUE THREAD

**Issue by agilma** [ThunderID/balin-dashboard#65]
- [x] laporan penjualan untuk sort tidak befungsi ![screen shot 2016-09-27 at 4 07 07 pm](https://cloud.githubusercontent.com/assets/4099329/18866982/7cf00ab8-84cc-11e6-8b1e-34cc5e234354.png)
- [x] **[enhancement]** dilaporan stok keluar tidak ada field stok keluar didalam tabel, sedangkan ada sort by stok keluar
  ![screen shot 2016-09-27 at 4 05 35 pm](https://cloud.githubusercontent.com/assets/4099329/18867016/acd0f9e0-84cc-11e6-843e-2fc067f75acb.png)
- [x] **[enhancement]** waktu klik ingatkan costumer dihalaman laporan abadoned cart lari ke halaman laporan penjualan
- [x] halaman laporan abadoned cart & laporan batal di sort by tagihan tidak bisa
- [x] halaman laporan batal sort by nota tidak jalan

**Comment by chelsymooy** [comment]
me here

**Comment by chelsymooy** [comment]
me no longer here

**Comment by budi7** [comment]
Doing

**Comment by budi7** [comment]
@chelsymooy  : help needed. dari backend sudah diberikan parameter sesuai dengan yang diminta di Api. Tapi sorting nya tdiak berfungsi. 

![screen shot 2016-09-30 at 2 12 51 pm](https://cloud.githubusercontent.com/assets/10555410/18983646/54f80030-8718-11e6-9611-bbf05edc85a4.png)

**Comment by chelsymooy** [comment]
@budi7 issue sort cleared

**Comment by budi7** [comment]
Ok @chelsymooy . Doing
